"""add code_tva and code_categorie to company

Revision ID: 94da9071c120
Revises: c14da286d2af
Create Date: 2026-09-25 14:23:00.386135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94da9071c120'
down_revision: Union[str, Sequence[str], None] = 'c14da286d2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('code_tva', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('code_categorie', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'code_categorie')
    op.drop_column('companies', 'code_tva')
    # ### end Alembic commands ###
