"""documents et profil societe

Revision ID: c14da286d2af
Revises: ec5dd4df1b5d
Create Date: 2026-09-22 10:50:33.450448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14da286d2af'
down_revision: Union[str, Sequence[str], None] = 'ec5dd4df1b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('minio_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'kind', name='uq_company_doc_kind')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('adresse', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('forme_juridique', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('capital', sa.Numeric(precision=14, scale=3), nullable=True))
    op.add_column('companies', sa.Column('date_creation', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('activite', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('dirigeant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'dirigeant')
    op.drop_column('companies', 'activite')
    op.drop_column('companies', 'date_creation')
    op.drop_column('companies', 'capital')
    op.drop_column('companies', 'forme_juridique')
    op.drop_column('companies', 'adresse')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
